-- Migración 027: añade campo 'uses' a cada output en forge_nodes (v1.4.0)
-- Solo modifica la columna outputs. No toca skills, prompts, inputs ni ningún otro campo.

UPDATE v57.forge_nodes SET outputs = '[{"key":"concept_seeds","type":"connection","label":"Concept Seeds","format":"structured","prompt":"Emit the curated concept seeds as structured data: id, title, one_liner, rationale for each.","image_gen":true,"image_gen_model":"comfyui:Character_Template_Generator","uses":{"inputs":[],"siblings_if_present":[]}},{"key":"exploration_summary","type":"asset","label":"Exploration Summary","format":"markdown","prompt":"Produce a markdown summary of the exploration: angles considered, seeds generated, rationale for each keep/cull.","uses":{"inputs":[],"siblings_if_present":[]}}]'::jsonb
WHERE node_key = '1.1' AND status = 'active';

UPDATE v57.forge_nodes SET outputs = '[{"key":"market_gap_analysis","type":"connection","label":"Market Gap Analysis","format":"gap_analysis","prompt":"Emit the market gap analysis as structured data: text summary and cultural_moment anchor.","uses":{"inputs":["concept_seeds"],"siblings_if_present":["competitive_scan"]}},{"key":"competitive_scan","type":"asset","label":"Competitive Scan","format":"markdown","prompt":"Produce a markdown table of 5–10 real titles with revenue, reviews, platform, and differentiators. Cite all sources.","uses":{"inputs":["concept_seeds"],"siblings_if_present":[]}},{"key":"audience_sizing","type":"asset","label":"Audience Sizing","format":"markdown","prompt":"Produce audience sizing: estimated addressable audience with methodology. Label as indicative if comparables-based.","uses":{"inputs":["concept_seeds"],"siblings_if_present":[]}}]'::jsonb
WHERE node_key = '1.2' AND status = 'active';

UPDATE v57.forge_nodes SET outputs = '[{"key":"positioning_statement","type":"connection","label":"Positioning Statement","format":"positioning","prompt":"Emit the positioning statement as structured data: ''For [audience] who [need], [project] is the [category] that [differentiator].''","uses":{"inputs":["concept_seeds","market_gap_analysis"],"siblings_if_present":[]}},{"key":"primary_persona","type":"asset","label":"Primary Persona","format":"markdown","prompt":"Produce the primary persona: name, age range, platforms, titles they love, motivations, and why this game fits them.","uses":{"inputs":["concept_seeds"],"siblings_if_present":[]}}]'::jsonb
WHERE node_key = '1.3' AND status = 'active';

UPDATE v57.forge_nodes SET outputs = '[{"key":"selected_seeds","type":"connection","label":"Selected Seeds","format":"list<concept_seed>","prompt":"Emit the curated list of seeds that advance. Same schema as concept_seed, survivors only.","uses":{"inputs":["concept_seeds"],"siblings_if_present":["selection_scorecard"]}},{"key":"selection_scorecard","type":"asset","label":"Selection Scorecard","format":"markdown","prompt":"Produce the scorecard: for each seed, rubric scores and a one-line verdict (advance / refine / drop) with reason.","uses":{"inputs":["concept_seeds","market_gap_analysis","positioning_statement"],"siblings_if_present":[]}}]'::jsonb
WHERE node_key = '1.4' AND status = 'active';

UPDATE v57.forge_nodes SET outputs = '[{"key":"elevator_line","type":"connection","label":"Elevator Line","format":"text","prompt":"Emit the locked elevator line as structured data: one sentence, no hedging.","uses":{"inputs":["concept_seed"],"siblings_if_present":["pitch_document"]}},{"key":"pitch_document","type":"asset","label":"Pitch Document","format":"docx","prompt":"Produce the one-page High-Level Pitch docx using V57 template: hook, elevator line, why now, production fit.","uses":{"inputs":["concept_seed","positioning_statement","market_gap_analysis"],"siblings_if_present":[]}}]'::jsonb
WHERE node_key = '2.1' AND status = 'active';

UPDATE v57.forge_nodes SET outputs = '[{"key":"concept_data","type":"connection","label":"Concept Data","format":"concept_data","prompt":"Emit the concept as structured data: title, one_liner, setting, core_fantasy, core_loop[], signature_mechanics[], differentiators[].","uses":{"inputs":["concept_seed"],"siblings_if_present":["concept_document"]}},{"key":"concept_document","type":"asset","label":"Concept Document","format":"docx","prompt":"Produce the two-page Concept Treatment docx using V57 template: Fact Sheet, One-Liner, Setting, Core Fantasy, Core Loop, Signature Mechanics, Levels, Art & Audio, Narrative Hook, Differentiators.","uses":{"inputs":["concept_seed","elevator_line","positioning_statement","market_gap_analysis"],"siblings_if_present":[]}}]'::jsonb
WHERE node_key = '2.2' AND status = 'active';

UPDATE v57.forge_nodes SET outputs = '[{"key":"financial_case","type":"connection","label":"Financial Case","format":"financial_case","prompt":"Emit the financial case as structured data: model, price_point, budget_range, funding_ask, use_of_funds[], break_even_note, key_assumptions[].","uses":{"inputs":["concept_data"],"siblings_if_present":["business_model"]}},{"key":"business_model","type":"asset","label":"Business Model","format":"markdown","prompt":"Produce the business model document: model rationale, pricing, budget breakdown, use-of-funds, break-even analysis with methodology shown.","uses":{"inputs":["concept_data","audience_sizing"],"siblings_if_present":[]}}]'::jsonb
WHERE node_key = '2.3' AND status = 'active';

UPDATE v57.forge_nodes SET outputs = '[{"key":"orientation_images","type":"asset","label":"Orientation Images","format":"png","prompt":"Generate 2–3 visual-orientation images. Lock a consistent palette across all. Specific references; negative-prompt genre clichés.","image_gen":true,"uses":{"inputs":["concept_data"],"siblings_if_present":["image_prompts"]}},{"key":"image_prompts","type":"asset","label":"Image Prompts","format":"markdown","prompt":"Produce the saved image prompts used, including the locked palette definition, for reproducibility.","uses":{"inputs":["concept_data"],"siblings_if_present":[]}}]'::jsonb
WHERE node_key = '2.4' AND status = 'active';

UPDATE v57.forge_nodes SET outputs = '[{"key":"investor_deck","type":"asset","label":"Investor Deck","format":"pptx","prompt":"Produce the investor deck using V57 cinematic template. Structure: Cover, Elevator, Setting, Fantasy+Loop, Mechanics, World, Differentiators+Why Now, Business Model, Production Fit, Closing. Images from Visual Orientation; palette from locked palette.","uses":{"inputs":["concept_data","elevator_line","orientation_images","financial_case"],"siblings_if_present":[]}}]'::jsonb
WHERE node_key = '2.5' AND status = 'active';

UPDATE v57.forge_nodes SET outputs = '[{"key":"review_verdict","type":"connection","label":"Review Verdict","format":"review_verdict","prompt":"Emit the review verdict as structured data: verdict (READY/CONDITIONS/NOT_READY), top_strengths[], top_risks[], coherence_ok.","uses":{"inputs":["investor_deck"],"siblings_if_present":["strategic_review"]}},{"key":"strategic_review","type":"asset","label":"Strategic Review","format":"markdown","prompt":"Produce the written strategic review: strengths with evidence, risks each with a mitigation, coherence audit across all artifacts, and final verdict with reasoning.","uses":{"inputs":["investor_deck","concept_data","financial_case"],"siblings_if_present":[]}}]'::jsonb
WHERE node_key = '2.6' AND status = 'active';

UPDATE v57.forge_nodes SET outputs = '[{"key":"gate_decision","type":"connection","label":"Gate Decision","format":"decision","prompt":"Emit the gate decision as structured data: verdict (ACCEPT/REFINE/BRANCH/KILL), refine_nodes[] if applicable.","uses":{"inputs":["investor_deck","review_verdict"],"siblings_if_present":[]}},{"key":"locked_concept_package","type":"asset","label":"Locked Concept Package","format":"artifact_bundle","prompt":"If verdict is ACCEPT: produce the locked concept package bundling all approved artifacts. If not ACCEPT: skip this output.","uses":{"inputs":["investor_deck"],"siblings_if_present":["gate_decision"]}}]'::jsonb
WHERE node_key = '2.7' AND status = 'active';
