-- ============================================================
-- Migration 039 — Registra los 43 skills de competencia faltantes de Pre-Producción
-- (nodos 3.1-3.21) en forge_skill_configs. Complementa la 038.
-- El r2_path apunta a  skills/<key>.md  en el bucket forge-system-prompts.
-- CONVENCIÓN: subir cada .md a ese bucket ANTES de que el nodo lo use.
-- Fuente: _PreProd 0707/skills_faltantes_R2/.  Idempotente: ON CONFLICT (key) DO UPDATE.
-- ============================================================

INSERT INTO v57.forge_skill_configs (key, r2_path, description) VALUES
  ('accessibility_design', 'skills/accessibility_design.md', 'Competency skill. Invoked by node 3.7 (UX / UI Design). Define the accessibility commitments the UX must honor — remappable input, colorblind-safe signaling, text scaling, subtitle standards, difficulty accommodations — as concrete requi...'),
  ('adaptive_audio_design', 'skills/adaptive_audio_design.md', 'Competency skill. Invoked by node 3.10 (Audio Direction). Specify how music and ambience respond to game state — intensity layers, transitions, stingers — so audio is a systemic feedback channel, not a static loop.'),
  ('adi_segmentation', 'skills/adi_segmentation.md', 'Competency skill. Invoked by node 3.9 (Art Direction Document). Split the Art Direction Intake into the eleven canonical ADI packages (11.1…11.11) so each downstream art discipline receives exactly its slice — the segmentation that makes...'),
  ('anti_pillar_definition', 'skills/anti_pillar_definition.md', 'Competency skill. Invoked by node 3.1 (Design Pillars). Name what the game must never become. Anti-pillars are the scope-creep brakes that make the pillars enforceable by stating their forbidden opposites.'),
  ('art_bible_writing', 'skills/art_bible_writing.md', 'Competency skill. Invoked by node 3.9 (Art Direction Document). Author the Art Bible: the single reference that fixes the game''s visual language — style, palette, shape, material, lighting, and the rules that keep every asset on-model.'),
  ('art_quality_assessment', 'skills/art_quality_assessment.md', 'Competency skill. Invoked by node 3.21 (VS Review). Judge whether produced art meets the Art Bible bar — an explicit, criteria-based verdict, used to review the vertical slice''s visual output.'),
  ('budget_estimation', 'skills/budget_estimation.md', 'Competency skill. Invoked by node 3.14 (Production Plan). Derive a defensible production budget from team size, timeline and scope — every figure carrying its assumption, nothing invented as sourced.'),
  ('build_spec_structuring', 'skills/build_spec_structuring.md', 'Competency skill. Invoked by node 3.16 (Prototype Specification). Shape the prototype''s build specification into the structured payload the build step consumes — the bridge from feature spec to buildable brief.'),
  ('difficulty_curve_design', 'skills/difficulty_curve_design.md', 'Competency skill. Invoked by node 3.2 (Core Gameplay). Design how challenge escalates across the core loop — the intended tension rhythm that mechanics and encounters will realize.'),
  ('difficulty_curve_mapping', 'skills/difficulty_curve_mapping.md', 'Competency skill. Invoked by node 3.5 (Level Design). Place the intended difficulty curve onto concrete levels/sections — mapping the designed tension rhythm to actual content beats.'),
  ('economy_balancing', 'skills/economy_balancing.md', 'Competency skill. Invoked by node 3.3 (Game Systems). Balance the in-game economy — sources, sinks, rates — so progression feels earned and no loop trivializes or starves the player.'),
  ('encounter_design', 'skills/encounter_design.md', 'Competency skill. Invoked by node 3.5 (Level Design). Design the discrete challenge units — encounters — that express the mechanics: their composition, intent, and how they teach or test.'),
  ('environment_design', 'skills/environment_design.md', 'Competency skill. Invoked by node 3.4 (World Design). Define the game''s places — biomes, districts, spaces — their identity, function, and how they express the world''s fiction and rules.'),
  ('environmental_storytelling', 'skills/environmental_storytelling.md', 'Competency skill. Invoked by node 3.5 (Level Design). Plan how the spaces themselves tell story — through layout, props, and traces — so narrative is discovered, not just told.'),
  ('faction_design', 'skills/faction_design.md', 'Competency skill. Invoked by node 3.4 (World Design). Define the world''s factions — their goals, values, conflicts, and how the player intersects them — as engines of narrative and gameplay tension.'),
  ('feature_prioritization', 'skills/feature_prioritization.md', 'Competency skill. Invoked by node 3.15 (Product Scope). Rank features by value against cost and risk so scope decisions are defensible — the discipline behind cutting to a shippable product.'),
  ('feel_statement_writing', 'skills/feel_statement_writing.md', 'Competency skill. Invoked by node 3.1 (Design Pillars). Write the 3–4 sentence statement of what the game feels like to play, second to second — the experiential north star the pillars and mechanics serve.'),
  ('gap_identification', 'skills/gap_identification.md', 'Competency skill. Invoked by node 3.18 (Prototype Playtest & Review). Surface what''s missing or broken between the intended design and the observed prototype — the honest diagnostic that drives the next iteration.'),
  ('hud_design', 'skills/hud_design.md', 'Competency skill. Invoked by node 3.7 (UX / UI Design). Design the heads-up display — what information the player needs, when, and how it''s shown without breaking immersion or readability.'),
  ('iap_catalog_design', 'skills/iap_catalog_design.md', 'Competency skill. Invoked by node 3.11 (Monetization Design). Structure the in-app-purchase catalog (when the model includes it) — items, pricing tiers, and the ethical guardrails — consistent with the monetization pillars.'),
  ('mechanic_specification', 'skills/mechanic_specification.md', 'Competency skill. Invoked by node 3.2 (Core Gameplay). Turn a designed mechanic into an engineering-ready spec — quantified rules, inputs/outputs, state, dependencies, and at least one testable acceptance criterion.'),
  ('mechanical_role_assignment', 'skills/mechanical_role_assignment.md', 'Competency skill. Invoked by node 3.6 (Characters). Assign each character/unit its mechanical role — how it plays differently — so the roster is a set of distinct decisions, not reskins.'),
  ('menu_architecture', 'skills/menu_architecture.md', 'Competency skill. Invoked by node 3.7 (UX / UI Design). Design the menu and navigation structure — the information architecture of every non-gameplay screen — for clarity and speed.'),
  ('milestone_definition', 'skills/milestone_definition.md', 'Competency skill. Invoked by node 3.14 (Production Plan). Define the production milestones — what ''done'' means at each — so the plan has verifiable checkpoints, not just a timeline.'),
  ('narrative_arc_design', 'skills/narrative_arc_design.md', 'Competency skill. Invoked by node 3.4 (World Design). Design the story''s structural arc — its acts, turns, and escalation — as the frame the world and characters hang on.'),
  ('narrative_arc_writing', 'skills/narrative_arc_writing.md', 'Competency skill. Invoked by node 3.6 (Characters). Write the character-level narrative — arcs, voices, key scenes — that realizes the designed structure with specific, playable content.'),
  ('onboarding_flow_design', 'skills/onboarding_flow_design.md', 'Competency skill. Invoked by node 3.7 (UX / UI Design). Design the first-time experience — how the game teaches itself — so new players reach competence without a wall of tutorial text.'),
  ('pacing_design', 'skills/pacing_design.md', 'Competency skill. Invoked by node 3.5 (Level Design). Design the rhythm of play across a session — the alternation of intensity and rest — so the experience breathes.'),
  ('palette_design', 'skills/palette_design.md', 'Competency skill. Invoked by node 3.9 (Art Direction Document). Lock the game''s colour palette by role — background, surface, accent, and any signaling roles — so colour is a system, not decoration.'),
  ('production_quality_bar_definition', 'skills/production_quality_bar_definition.md', 'Competency skill. Invoked by node 3.13 (Vertical Slice Specification). Define the quality bar the vertical slice must hit — the concrete ''this is what shippable looks like'' standard for the slice.'),
  ('production_readiness_assessment', 'skills/production_readiness_assessment.md', 'Competency skill. Invoked by node 3.15 (Product Scope). Assess whether the project is ready to leave pre-production and enter full production — a criteria-based verdict on the whole package.'),
  ('real_numbers_constraint', 'skills/real_numbers_constraint.md', 'Competency skill. Invoked by node 3.2 (Core Gameplay). Enforce that every quantifiable design value is a real, stated number — not ''fast'', ''a lot'', ''balanced'' — so specs are buildable and testable.'),
  ('risk_adjusted_planning', 'skills/risk_adjusted_planning.md', 'Competency skill. Invoked by node 3.15 (Product Scope). Adjust the production plan for its risks — buffers, contingencies, and cut lines — so the schedule survives contact with reality.'),
  ('risk_register_writing', 'skills/risk_register_writing.md', 'Competency skill. Invoked by node 3.14 (Production Plan). Author the risk register — the named, rated, mitigated list of what could derail the project — as a living production artifact.'),
  ('scope_definition', 'skills/scope_definition.md', 'Competency skill. Invoked by node 3.15 (Product Scope). Define the product''s scope — what is and isn''t in the shippable version — as an explicit, defensible boundary.'),
  ('sfx_catalog_structuring', 'skills/sfx_catalog_structuring.md', 'Competency skill. Invoked by node 3.10 (Audio Direction). Structure the sound-effects catalog — the organized list of every sound the game needs, with its trigger and intent — so audio production has a spec.'),
  ('stats_and_abilities_design', 'skills/stats_and_abilities_design.md', 'Competency skill. Invoked by node 3.3 (Game Systems). Design the numeric stats and abilities that tune characters/units into their assigned roles — the balance layer over the role assignment.'),
  ('style_guide_production', 'skills/style_guide_production.md', 'Competency skill. Invoked by node 3.9 (Art Direction Document). Produce the production style guide — the operational rules artists follow daily — derived from the Art Bible into checkable do/don''ts.'),
  ('success_criteria_evaluation', 'skills/success_criteria_evaluation.md', 'Competency skill. Invoked by node 3.18 (Prototype Playtest & Review). Evaluate the prototype against its stated success criteria — the objective pass/fail read that grounds the gate decision.'),
  ('success_criteria_writing', 'skills/success_criteria_writing.md', 'Competency skill. Invoked by node 3.16 (Prototype Specification). Write the prototype''s success criteria — the binary, externally-observable statements that define whether the prototype worked.'),
  ('unity_project_structure', 'skills/unity_project_structure.md', 'Competency skill. Invoked by node 3.17 (Prototype Build). Define the Unity project''s structure — folders, assemblies, naming, test layout — so the build starts organized and the manual MCP handoff has a valid target.'),
  ('unreal_project_structure', 'skills/unreal_project_structure.md', 'Competency skill. Invoked by node 3.17 (Prototype Build). Define the Unreal project''s structure — module layout, content organization, naming, and test setup — when the chosen engine is Unreal.'),
  ('v57_image_prompt_architecture', 'skills/v57_image_prompt_architecture.md', 'Competency skill. Invoked by node 3.9 (Art Direction Document). Architect the image-generation prompts the ADI produces — structured, palette-locked, reproducible prompts that hold the art direction across every generated image.')
ON CONFLICT (key) DO UPDATE SET
  r2_path     = EXCLUDED.r2_path,
  description = EXCLUDED.description,
  updated_at  = now();
