function buildCodePrompt(targetEngine, gameContext) {
  switch (targetEngine) {
    case 'unity':   return buildUnityPrompt(gameContext)
    case 'unreal':  return buildUnrealPrompt(gameContext)
    case 'godot':   return buildGodotPrompt(gameContext)
    case 'phaser':
    default:        return buildPhaserPrompt(gameContext)
  }
}

function buildUnityPrompt(ctx) {
  return `You are an expert Unity game developer (C#, Unity 2022.3 LTS).

Generate 4 complete, compilable C# Unity scripts for this game based on the GDD.
Name all classes using the actual game name and characters from the GDD.

GAME CONTEXT:
${JSON.stringify(ctx, null, 2)}

SCRIPTS TO GENERATE:

1. [GameName]PlayerController.cs
   - MonoBehaviour attached to the Player GameObject
   - Rigidbody2D or CharacterController based movement
   - Left/right movement, jumping with ground detection
   - Implement the FIRST core mechanic from GDD mechanics array
   - Health system with the number of lives from GDD
   - SerializeField for all tunable values (speed, jumpForce, etc.)
   - XML documentation comments on all public methods
   - TODO comments where developer must add animations, VFX, SFX

2. [GameName]EnemyController.cs
   - Base enemy class + specific behavior per enemy type from GDD
   - Each enemy type from GDD characters array gets its own behavior
   - Patrol AI: move between waypoints or bounce off walls
   - Player detection with configurable detection radius
   - Health and damage system
   - OnDeath event for spawning effects or drops

3. [GameName]GameManager.cs
   - Singleton pattern (Instance property)
   - Game state enum: MainMenu, Playing, Paused, GameOver, Victory
   - Health/lives tracking matching GDD
   - Level progression system
   - Events: OnHealthChanged, OnGameStateChanged, OnLevelComplete
   - SceneManager integration for level transitions

4. ForgeManifest.cs
   - Static class, auto-generated by Forge — mark with comment DO NOT EDIT
   - Constants from GDD: game name, genre, version, target engine
   - String arrays: mechanics names, character names, level names
   - Build metadata: generated date, Forge version

UNITY C# RULES:
- All scripts must compile without errors in Unity 2022.3 LTS
- Use UnityEngine namespace correctly
- SerializeField for inspector-exposed private fields
- Use [Header("Section Name")] to organize inspector fields
- Use Awake() for self-initialization, Start() for cross-references
- Use FixedUpdate() for physics, Update() for input
- No hardcoded magic numbers — use named constants or SerializeField
- Add [RequireComponent] attributes where appropriate
- Mark TODO items as: // TODO: [description of what developer must add]
- Use proper C# conventions: PascalCase for classes/methods, camelCase for fields

RETURN FORMAT:
Return ONLY valid JSON. No markdown, no backticks outside the JSON.
All C# code strings must have newlines as \\n and quotes escaped as \\".

{
  "engine": "unity",
  "files": [
    {
      "filename": "[GameName]PlayerController.cs",
      "description": "Player movement and core mechanic controller",
      "content": "using UnityEngine;\\n\\npublic class..."
    },
    {
      "filename": "[GameName]EnemyController.cs",
      "description": "Enemy AI and behavior controller",
      "content": "using UnityEngine;\\n\\npublic class..."
    },
    {
      "filename": "[GameName]GameManager.cs",
      "description": "Game state and progression manager",
      "content": "using UnityEngine;\\n\\npublic class..."
    },
    {
      "filename": "ForgeManifest.cs",
      "description": "Auto-generated GDD constants — do not edit",
      "content": "// AUTO-GENERATED BY FORGE\\n\\npublic static class..."
    }
  ],
  "architecture_md": "# [GameName] — Unity Architecture\\n\\n..."
}`
}

function buildGodotPrompt(ctx) {
  return `You are an expert Godot 4 game developer (GDScript).
Generate 3 GDScript files for this game based on the GDD.
GAME CONTEXT: ${JSON.stringify(ctx, null, 2)}

Return ONLY valid JSON:
{
  "engine": "godot",
  "files": [
    { "filename": "player.gd", "description": "...", "content": "..." },
    { "filename": "enemy.gd", "description": "...", "content": "..." },
    { "filename": "game_manager.gd", "description": "...", "content": "..." }
  ],
  "architecture_md": "..."
}`
}

function buildUnrealPrompt(ctx) {
  return `You are an expert Unreal Engine 5 developer (C++).
Generate a player character header and implementation for this game.
GAME CONTEXT: ${JSON.stringify(ctx, null, 2)}

Return ONLY valid JSON:
{
  "engine": "unreal",
  "files": [
    { "filename": "[GameName]Character.h", "description": "...", "content": "..." },
    { "filename": "[GameName]Character.cpp", "description": "...", "content": "..." }
  ],
  "architecture_md": "..."
}`
}

function buildPhaserPrompt(ctx) {
  return `You are an expert Phaser.js 3 game developer.

Generate a COMPLETE, WORKING Phaser.js 3 platformer game based on the GDD provided.

MANDATORY REQUIREMENTS:
1. Use Phaser.Scene classes (NOT function-based scenes)
2. Create PreloadScene, GameScene, and GameOverScene classes
3. Player must have: left/right movement, jumping, gravity
4. Include at least 2 enemy instances with patrol AI
5. Include platforms using staticGroup with colored rectangles
6. Implement the FIRST core mechanic from the GDD
7. Player uses keyboard: arrow keys for movement, SHIFT or E for special mechanic
8. Camera must follow the player
9. Include health system (3 lives) and game over logic
10. Name ALL classes using the actual game characters from the GDD

CRITICAL - PLACEHOLDER GRAPHICS:
- NEVER use this.physics.add.sprite() with a texture key
- NEVER load images in preload()
- NEVER call .create() on a staticGroup with a texture key
- For player: this.add.rectangle() then this.physics.add.existing(rect)
- For static platform: this.add.rectangle() then this.physics.add.existing(rect, true)
- For enemy: this.add.rectangle() then this.physics.add.existing(rect)

Return ONLY valid JSON:
{
  "engine": "phaser",
  "files": [
    { "filename": "game.js", "description": "Complete Phaser.js 3 game", "content": "..." }
  ],
  "architecture_md": "..."
}`
}

module.exports = { buildCodePrompt }
